// 256-entry signed 8-bit sine ROM (values in [-127,127]).
// Registered read: q is valid one clock after addr.
// Table is generated by vc709/python/gen_sine_rom.py -> sine_rom.mem
module sine_rom (
    input  wire              clk,
    input  wire [7:0]        addr,
    output reg  signed [7:0] q
);
    reg [7:0] rom [0:255];
    initial $readmemh("sine_rom.mem", rom);
    always @(posedge clk) q <= rom[addr];
endmodule
